import Head from "next/head";
import Navigation from "@/components/navigation";

export default function Flashcards() {
  return (
    <>
      <Head>
        <title>Flashcards - Computer Architecture Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navigation /> 

          {/* ----- Chapter 1 Topics ----- */}

          <div className="my-32 grid grid-cols-4 gap-x-4 gap-y-4 border-4 text-center border-white">
            <div className="border-4 font-bold bg-blue-300 border-blue-500 col-span-4 select-none"> Chapter 1 - Performance Evaluation </div>

            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Execution Time </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Performance = ... </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Baseline </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Amdahl's Law </div>

            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900"> 
              <div class="flex items-center justify-center h-full select-none">
                The time between the start and the completion of a task.
              </div>     
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                1 / Execution_Time <br />
                The performance of your program will be inversely proportional to the execution time of your program. 
              </div>    
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>    
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>                
            </div>

            {/* ----- Chapter 2 Topics ----- */}

            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Dennard Scaling </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Performance </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Execution Time </div>
            <div className="border-4 font-bold bg-blue-300 border-sky-500 select-none"> Amdahl's Law </div>

            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900"> 
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>    
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>    
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 text-blue-900 bg-blue-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>
          </div>

          <div className="my-32 grid grid-cols-4 gap-x-4 gap-y-4 border-4 text-center border-white">
            <div className="border-4 font-bold bg-purple-300 border-purple-500 col-span-4 select-none"> Chapter 2 - ISA Introduction </div>

            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Dennard Scaling </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Performance </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Execution Time </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Amdahl's Law </div>

            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 h-32 text-purple-900 bg-purple-900"> 
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 h-32 text-purple-900 bg-purple-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 h-32 text-purple-900 bg-purple-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 h-32 text-purple-900 bg-purple-900">
              <div class="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>
            </div>

            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Dennard Scaling </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Performance </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Execution Time </div>
            <div className="border-4 font-bold bg-purple-300 border-purple-500 select-none"> Amdahl's Law </div>

            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 ease-in-out h-32 text-purple-900 bg-purple-900"> 
              <div className="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>            
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 ease-in-out h-32 text-purple-900 bg-purple-900">
              <div className="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>                
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 ease-in-out h-32 text-purple-900 bg-purple-900">
              <div className="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>     
            </div>
            <div className="border-4 border-purple-500 hover:bg-opacity-0 transition duration: 0 ease-in-out h-32 text-purple-900 bg-purple-900">
              <div className="flex items-center justify-center h-full select-none">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
                nihil assumenda doloribus voluptas eaque praesentium sequi
              </div>     
            </div>
          </div>

        </div>
      </main>
    </>
  );
}
