import Head from "next/head";
import Navigation from "@/components/navigation";

export default function Flashcards() {
  return (
    <>
      <Head>
        <title>Flashcards - Computer Architecture Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navigation /> 

          <div className="my-32 grid grid-cols-4 gap-x-4 gap-y-4 border-4 text-center border-white">
            <div className="border-4 bg-blue-300 border-sky-500"> Dennard Scaling </div>
            <div className="border-4 bg-blue-300 border-sky-500"> Performance </div>
            <div className="border-4 bg-blue-300 border-sky-500"> Execution Time </div>
            <div className="border-4 bg-blue-300 border-sky-500"> Amdahl's Law </div>

            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 bg-blue-900"> 
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 bg-blue-900">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 bg-blue-900">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
            </div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 transition duration: 0 h-32 bg-blue-900">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
            </div>

            <div className="border-4 border-sky-500">(3,1)</div>
            <div className="border-4 border-sky-500">(3,2)</div>
            <div className="border-4 border-sky-500">(3,3)</div>
            <div className="border-4 border-sky-500">(3,4)</div>

            <div className="border-4 border-sky-500 hover:bg-opacity-0 h-32 bg-blue-900">(4,1)</div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 h-32 bg-blue-900">(4,2)</div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 h-32 bg-blue-900">(4,3)</div>
            <div className="border-4 border-sky-500 hover:bg-opacity-0 h-32 bg-blue-900">(4,4)</div>
          </div>

          {/* <div className="mx-32 my-32 text-xl font-bold text-center">
            Lecture 1: Evaluation Performance
          </div>

          <div className="h-8 w-64 mx-32 -my-32 border-4 border-sky-500 bg-blue-900 text-white text-center select-none font-bold">
            Amdahl's Law
          </div>
          <div className="h-32 w-64 mx-32 my-32 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900 transition duration: 0 text-center select-none">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
          </div>

          <div className="h-8 w-64 mx-96 -my-72 border-4 border-sky-500 bg-blue-900 text-white text-center select-none font-bold">
            Dennard Scaling
          </div>
          <div className="h-32 w-64 mx-96 my-72 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900 transition duration: 0 text-center select-none">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
          </div> */}

          {/* <div className="h-8 w-64 mx-96 -my-72 border-4 border-sky-500 bg-blue-900 text-white text-center select-none font-bold">
            Dennard Scaling
          </div>
          <div className="h-32 w-64 mx-96 my-72 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900 transition duration: 0 text-center select-none">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
          </div> */}

          {/* <div className="h-8 w-64 mx-32 my-36 border-4 border-sky-500 bg-blue-900 text-white text-center select-none font-bold">
            Define Dennard Scaling
          </div>
          <div className="h-32 w-64 mx-32 -my-36 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900 transition duration: 0 text-center select-none">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
              nihil assumenda doloribus voluptas eaque praesentium sequi
          </div>

          <div className="h-8 w-64 mx-32 my-40 border-4 border-sky-500 bg-blue-900 text-white text-center select-none font-bold">
            Define Data Hazards
          </div>
          <div className="h-32 w-64 mx-32 -my-40 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900 transition duration: 0 text-center select-none">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
            nihil assumenda doloribus voluptas eaque praesentium sequi
          </div> */}

        </div>
      </main>
    </>
  );
}


{/* <div className="h-32 w-64 m-12 mt-32 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900">
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
  nihil assumenda doloribus voluptas eaque praesentium sequi
  </div> */}
{/* <div className="h-32 w-64 m-12 mt-32 border-4 border-sky-500 hover:bg-opacity-0 bg-blue-900 text-blue-900">
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis eum
  nihil assumenda doloribus voluptas eaque praesentium sequi
  </div> */}