import Head from "next/head";
import Navigation from "@/components/navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="%PUBLIC_URL%/adobe-fonts.css" />
      </Head>
      <main>
        <div >
          <Navigation />


          <div class="mt-20 p-5 w-screen h-90 bg-background-main" > 

            <div class=" bg-main-img w-auto h-[35rem] rounded-3xl flex justify-center ">
              <div class="flex flex-col grid content-center" > 
                <div>
                  <p class="text-white font-owners text-6xl" > learn and improve</p>
                </div>
                <div>
                  <p class="text-white font-owners text-6xl" > your linux and core computing </p>
                </div>
                <div>
                  <p class="text-white font-owners text-6xl" > knowledge </p>
                </div>
                
              </div>
            </div>

            <div class="w-full h-1 bg-header-main mt-4"> </div>
          </div>



          <div class=" pr-5 pb-5 pl-5 w-screen h-90 bg-background-main" > 

            <div class="flex flex-row"> 

              <div class=" bg-header-main w-[60rem] h-[25rem] rounded-3xl flex justify-center mr-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                </div>
              </div>

              <div class=" bg-main-img w-full h-[25rem] rounded-3xl flex justify-center ml-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                 
                  
                </div>
              </div>

            </div>
            <div class="w-full h-1 bg-header-main mt-4"> </div>
          </div>









          <div class=" pr-5 pb-5 pl-5 w-screen h-90 bg-background-main" > 

            <div class="flex flex-row"> 

              <div class=" bg-main-img w-full h-[25rem] rounded-3xl flex justify-center mr-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                </div>
              </div>

              <div class=" bg-header-main w-[60rem] h-[25rem] rounded-3xl flex justify-center ml-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                </div>
              </div>

            </div>
            <div class="w-full h-1 bg-header-main mt-4"> </div>
          </div>





          <div class=" pr-5 pb-5 pl-5 w-screen h-90 bg-background-main" > 

            <div class="flex flex-row"> 

              <div class=" bg-header-main w-[60rem] h-[25rem] rounded-3xl flex justify-center mr-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                </div>
              </div>

              <div class=" bg-main-img w-full h-[25rem] rounded-3xl flex justify-center ml-2">
                <div class="flex flex-col grid content-center" > 
                  <div>
                    <p class="text-white font-owners text-6xl" > learn and improve</p>
                  </div>
                
                  
                </div>
              </div>

            </div>
            <div class="w-full h-1 bg-header-main mt-4"> </div>
          </div>
          

          <div class=" pr-5 pb-5 pl-5 w-screen h-90 bg-background-main" > 

            <div class=" bg-main-img w-auto h-[35rem] rounded-3xl flex justify-center ">
              <div class="flex flex-col grid content-center" > 
                <div>
                  <p class="text-white font-owners text-6xl" > learn and improve</p>
                </div>
                <div>
                  <p class="text-white font-owners text-6xl" > your linux and core computing </p>
                </div>
                <div>
                  <p class="text-white font-owners text-6xl" > knowledge </p>
                </div>
                
              </div>
            </div>

            <div class="w-full h-1 bg-header-main mt-4"> </div>
            
          </div>






        </div> 
      </main>
    </>
  );
}
