import Head from "next/head";
import Navigation from "@/components/navigation";

export default function Linux() {
  return (
    <>
      <Head>
        <title>Linux - Computer Architecture Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
      </main>
    </>
  );
}
